import Navbar from '@/components/Navbar';
import './globals.scss';
import { Inter } from 'next/font/google';
import Footer from '@/components/Footer';
import Container from '@/components/Container';
import { ThemeProvider } from '@/components/ThemeContext';
import AuthProvider from '@/components/AuthProvider';
import { ToastProvider } from '@/components/ToastProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  
  return (
    <html lang='en'>
      <body className={inter.className}>
        <AuthProvider>
          <ThemeProvider>
            <Container>
              <Navbar />
              <ToastProvider />
              {children}
              <Footer />
            </Container>
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
